### ISSUE TITLE
Add XXXHDPI support

### ISSUE THREAD

**Issue by BlitzKraig** [BlitzKraig/AndroidResizer#16]

**Comment by oktayelipek** [comment]
high priority update.

**Comment by BlitzKraig** [comment]
Sorry, I've been meaning to get round to working on this, but I've not had time. Currently putting in a lot of overtime at work, but I'll look to doing this at the weekend. I could complete just this ticket and release a quick version if that would be helpful for you?

**Comment by BlitzKraig** [comment]
Hi @oktayelipek , v1.4 can now be found in the Releases tab, and includes XXXHDPI support.

Let me know if you have any issues.

**Comment by oktayelipek** [comment]
Hi @BlitzKraig , great news. :)
