### ISSUE TITLE
missing linux or .jar on releases

### ISSUE THREAD

**Issue by sibelius** [BlitzKraig/AndroidResizer#28]
In the latest releases there is no .jar file or a linux version of this lib

could u please fix this?

**Comment by BlitzKraig** [comment]
Apologies, the download stats showed that nobody was downloading the jar, so I forgot all about it. I'll look at updating this over the weekend and getting a new version up.

**Comment by BlitzKraig** [comment]
Sorry Sibelius, just came across this again, forgot all about it. This project has been dead for a while at this point, but I'm planning on creating a better cross-platform alternative with electron soon.
